# Use Node.js Alpine as the base image
FROM node:22-slim

# Set the working directory
WORKDIR /app

# Copy package files and install dependencies
# COPY package.json package-lock.json ./
COPY package.json ./
RUN npm install --omit=dev

# Copy the rest of the app code
COPY . .

# Expose the port your server listens on
EXPOSE 3000

# Start the application
CMD ["node", "server.js"]